In [3]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
type(a)

numpy.ndarray

In [12]:
numbers=[1,2,3,4,5,6,7,8
]
numbers

[1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
numbers_array = np.array(numbers)
numbers_array

array([1, 2, 3, 4, 5, 6, 7, 8])

2D array

In [52]:
arr = np.array([
    [1,2,3],
    [3,4,5],
    [7,8,9]])
print(arr)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [21]:
#generating values in numpy
#zeros
zero_array = np.zeros(5, dtype=int)
zero_array

array([0, 0, 0, 0, 0])

In [31]:
#Ones
ones_array = np.ones(10,dtype= int)
ones_array

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
#arange 
range_data = np.arange(0,11,2)
range_data

array([ 0,  2,  4,  6,  8, 10])

In [29]:
zero_2d_array = np.zeros((5,2),dtype=int)
zero_2d_array 

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [33]:
ones_2d_array = np.ones((5,2),dtype=int)
ones_2d_array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

#Reshape and Ravel


In [36]:
#ravel function is used to convert 2D array to 1D
ravel_array = np.ravel(ones_2d_array)
ravel_array

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
reshaped = ravel_array.reshape(2,5)
reshaped

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
print(arr)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [44]:
arr.shape

(3, 3)

In [46]:
arr.ndim

2

In [48]:
arr.size

9

In [54]:
arr.dtype

dtype('int32')

#converting array into list

In [64]:
numbers = []
for num in reshaped:
    numbers.append(num)

numbers

[array([1, 1, 1, 1, 1]), array([1, 1, 1, 1, 1])]

In [66]:
type(numbers)

list

In [70]:
#unpacking list
print(*numbers)

[1 1 1 1 1] [1 1 1 1 1]


Indexing and Slicing

In [73]:
name = "Sizan"
print(name[0:4:2])

Sz


In [77]:
'''
Concept needed for conditional filtering using slicnig
positive index starts from 0
negative index starrts from -1
slicing is used for feature Extraction or Sample Data Extraction'''
no = np.array([1,2,3,4,5,6,7,8,9])
no

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
no[0:5]

array([1, 2, 3, 4, 5])

In [81]:
no[0:5:2]


array([1, 3, 5])

In [83]:
#reversing
no[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [85]:
no[::6]

array([1, 7])

In [87]:
no[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
data = np.array([[1,2,3,4],
                [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
               )


In [93]:
#simple slicing
data[1:4]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [95]:
#Slicing using Row and Coloumn to 2d array
data[0:3,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [97]:
data[0:3,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

#Boolean indexing

In [69]:
salary = np.array([1000,2000,3000,4000,5000,6000,7000])
salary


array([1000, 2000, 3000, 4000, 5000, 6000, 7000])

In [71]:
filtered_salary =  salary>2000
filtered_salary


array([False, False,  True,  True,  True,  True,  True])

In [73]:
salary[filtered_salary]

array([3000, 4000, 5000, 6000, 7000])

In [67]:
employees = np.array(["Ram","Ram","Shyam","Hari","Shyam"
])
employees

array(['Ram', 'Ram', 'Shyam', 'Hari', 'Shyam'], dtype='<U5')

In [122]:
filtered_employee = employees == "Ram"
filtered_employee

array([ True,  True, False, False, False])

In [126]:
print(employees[filtered_employee])

['Ram' 'Ram']


#Array Broadcasting

In [ ]:
'''
Rules for array broadcasting
-----------------------------
Array -> size equal
Rule 2 -> either size equal or an array should have only one element
'''



In [129]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a+b)

[2 4 6 8]


In [137]:
number_one = np.array([
    [1,2,3],
    [5,6,7]
])
number_one.shape

(2, 3)

In [139]:
number_two = np.array([4,5,6])
number_two.shape

(3,)

In [141]:
sum = number_one + number_two
print(sum)

[[ 5  7  9]
 [ 9 11 13]]


In [11]:
no = np.array([1,2,3,4,5,6,7,8,9])
no

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
no.max()

9

In [15]:
no.min()

1

In [19]:
no.mean(dtype=int)

5

In [25]:
no.sum()


45

In [39]:
no.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
no

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#2D list slicing
num = np.array([[1,2,3],[4,5,6],[7,8,9]
    ])
num

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
#Row slicing
num[0:3,1]

array([2, 5, 8])

In [61]:
#coloumn slicing
num[0:3,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])